# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
use_frameworks!

target 'UIViewAnimations' do
pod 'pop', '~> 1.0'
end

target 'UIViewAnimationsTests' do

end

