# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'Homework8Project' do

pod 'Alamofire'

end

target 'Homework8ProjectTests' do

end

